# Generated by Django 6.0.1 on 2026-02-27 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creatorcategory_creatorprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, help_text='Facebook profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='instagram_profile',
            field=models.URLField(blank=True, help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tikTok_profile',
            field=models.URLField(blank=True, help_text='TikTok profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='x_profile',
            field=models.URLField(blank=True, help_text='X (Twitter) profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='youtube_profile',
            field=models.URLField(blank=True, help_text='YouTube channel URL', validators=[django.core.validators.URLValidator()]),
        ),
    ]
