# Generated by Django 6.0.1 on 2026-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletkyc',
            name='full_name',
        ),
        migrations.AddField(
            model_name='walletkyc',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'BANK'), ('MOBILE_MONEY', 'MOBILE_MONEY')], default='MOBILE_MONEY', max_length=20),
        ),
    ]
