# Generated by Django 6.0.1 on 2026-02-03 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
        ('wallets', '0006_remove_payment_wallets_pay_referen_ef82d4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tier_name', models.CharField(choices=[('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3')], default='T1', max_length=30)),
                ('tier_type', models.CharField(choices=[('ONE_TIME_TIP', 'One Time Tip'), ('SUBSCRIPTION', 'Subscription')], db_index=True, default='ONE_TIME_TIP', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.CharField(help_text='Short Message to Payer', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='creators.creatorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
