# Generated by Django 6.0.1 on 2026-02-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_dispute_provider_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentwebhooklog',
            name='wallets_pay_provide_059773_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhooklog',
            name='wallets_pay_created_363021_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhooklog',
            name='wallets_pay_payment_4542f4_idx',
        ),
        migrations.RemoveField(
            model_name='paymentwebhooklog',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
        migrations.DeleteModel(
            name='PaymentWebhookLog',
        ),
    ]
