# Generated by Django 6.0.1 on 2026-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_remove_paymentwebhooklog_wallets_pay_provide_059773_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpayoutaccount',
            name='account_name',
            field=models.CharField(default='tests', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletpayoutaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
