# Generated by Django 6.0.1 on 2026-02-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_walletpayoutaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='payout_interval_days',
            field=models.PositiveIntegerField(choices=[(7, 'Weekly'), (14, 'Bi-Weekly'), (30, 'Monthly')], default=30),
        ),
    ]
