# Generated by Django 6.0.1 on 2026-02-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_wallet_payout_interval_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='kyc_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='kyc_level',
            new_name='wallet_level',
        ),
    ]
