# Generated by Django 6.0.1 on 2026-02-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_rename_kyc_verified_wallet_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_level',
            new_name='level',
        ),
    ]
