# Generated by Django 6.0.1 on 2026-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20),
        ),
    ]
