# Generated by Django 6.0.1 on 2026-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
