# Generated by Django 6.0.1 on 2026-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('creator', 'Creator'), ('patron', 'Patron'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20),
        ),
    ]
