# Generated by Django 6.0.1 on 2026-02-02 08:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0005_remove_walletkyc_full_name_walletkyc_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(help_text='reference for patron-facing purposes', max_length=100)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Payment ID from the payment provider', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in the specified currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('ZMW', 'Zambian Kwacha'), ('EUR', 'Euro')], default='ZMW', max_length=3)),
                ('amount_captured', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount successfully captured', max_digits=20)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded to patron', max_digits=20)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('captured', 'Captured'), ('partially_captured', 'Partially Captured'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('requires_action', 'Requires Action'), ('requires_confirmation', 'Requires Confirmation'), ('disputed', 'Disputed'), ('in_reconciliation', 'IN_RECONCILIATION'), ('paid', 'Paid'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('provider', models.CharField(choices=[('pawapay', 'Pawapay'), ('custom', 'custom'), ('lipila', 'Lipila Online')], db_index=True, max_length=30)),
                ('isp_provider', models.CharField(blank=True, choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], db_index=True, max_length=30, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card')], db_index=True, max_length=30, null=True)),
                ('patron_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patron_name', models.CharField(blank=True, max_length=255)),
                ('patron_phone', models.CharField(blank=True, max_length=50)),
                ('order_reference', models.CharField(blank=True, db_index=True, help_text='Reference to the associated order in your system', max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged by the payment provider', max_digits=20, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after provider fees', max_digits=20, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict, help_text='Raw response data from payment provider')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_score', models.FloatField(blank=True, help_text='Risk assessment score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('requires_3ds', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference', 'status'], name='payments_pa_referen_e9ad27_idx'), models.Index(fields=['patron_email', 'created_at'], name='payments_pa_patron__fbb5b0_idx'), models.Index(fields=['order_reference'], name='payments_pa_order_r_73d860_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'), models.Index(fields=['created_at', 'status'], name='payments_pa_created_bc9e4b_idx'), models.Index(fields=['amount', 'currency'], name='payments_pa_amount_e7ee9e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_captured__lte', models.F('amount'))), name='amount_captured_lte_amount'), models.CheckConstraint(condition=models.Q(('amount_refunded__lte', models.F('amount_captured'))), name='amount_refunded_lte_amount_captured')],
            },
        ),
    ]
