# Generated by Django 6.0.1 on 2026-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0007_tier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_patron__fbb5b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_order_r_73d860_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_provide_cc7861_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='patron_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patron_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patron_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patron_phone', 'created_at'], name='payments_pa_patron__63d318_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='captured_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
    ]
