# Generated by Django 6.0.1 on 2026-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payments_pa_patron__fbb5b0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='isp_provider',
            field=models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], db_index=True, default='MTN_MOMO_ZMB', max_length=30),
            preserve_default=False,
        ),
    ]
